export const UserActionTypes = {
  USER_LOADED: "USER_LOADED",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  AUTH_ERROR: "AUTH_ERROR",
  LOGOUT: "LOGOUT",
  UPLOAD_PHOTO: "UPLOAD_PHOTO",
  DELETE_POST: "DELETE_POST",
};
